// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practica3CRUD.Models;

namespace Practica3CRUD.Migrations
{
    [DbContext(typeof(Practica3CRUDContext))]
    [Migration("20181116203744_secondmigration")]
    partial class secondmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Practica3CRUD.Models.Direccion", b =>
                {
                    b.Property<int>("Iddireccion")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Calle");

                    b.Property<int>("Idpersona");

                    b.Property<string>("Municipio");

                    b.Property<int?>("PersonasId");

                    b.Property<string>("Provincia");

                    b.Property<string>("Sector");

                    b.HasKey("Iddireccion");

                    b.HasIndex("PersonasId");

                    b.ToTable("Direccion");
                });

            modelBuilder.Entity("Practica3CRUD.Models.Personas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("Direccion");

                    b.Property<int>("Edad");

                    b.Property<string>("Nombre");

                    b.Property<string>("Telefono");

                    b.HasKey("Id");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Practica3CRUD.Models.Direccion", b =>
                {
                    b.HasOne("Practica3CRUD.Models.Personas", "Personas")
                        .WithMany("direccion")
                        .HasForeignKey("PersonasId");
                });
#pragma warning restore 612, 618
        }
    }
}
